ALTER TABLE issues DROP CONSTRAINT ISSUE_FKEY ;
ALTER TABLE issues DROP CONSTRAINT ISSUE_GKEY ;
ALTER TABLE return DROP CONSTRAINT RETURN_FKEY;
ALTER TABLE return DROP CONSTRAINT RETURN_GKEY;
ALTER TABLE customer DROP CONSTRAINT CUSTOMER_PKEY ;
ALTER TABLE issues DROP CONSTRAINT ISSUE_PKEY ;
ALTER TABLE book DROP CONSTRAINT BOOK_PKEY;
ALTER TABLE return  DROP CONSTRAINT RETURN_PKEY;
----------------------------------------------------
-- DROPPING TABLES
----------------------------------------------------
DROP TABLE customer;
DROP TABLE issues;
DROP TABLE return;
DROP TABLE book;
DROP sequence it1;
DROP sequence it2;
